-- Daily Closeout Register database setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.closeout_entries (
  id bigint generated by default as identity primary key,
  closeout_date date not null,
  hotel text not null,
  platform text not null,
  status text not null check (status in ('Done', 'No', 'N/A')),
  email_time time,
  completion_time time,
  agent text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.extranet_hotels (
  id bigint generated by default as identity primary key,
  platform text not null,
  hotel_name text not null,
  hotel_type text check (hotel_type in ('Contract', 'Promo', 'Contract + Promo') or hotel_type is null),
  created_at timestamptz not null default now(),
  unique (platform, hotel_name)
);

alter table public.closeout_entries enable row level security;
alter table public.extranet_hotels enable row level security;

drop policy if exists "Public can read closeout entries" on public.closeout_entries;
create policy "Public can read closeout entries"
  on public.closeout_entries for select to anon, authenticated using (true);

drop policy if exists "Public can insert closeout entries" on public.closeout_entries;
create policy "Public can insert closeout entries"
  on public.closeout_entries for insert to anon, authenticated with check (true);

drop policy if exists "Public can delete closeout entries" on public.closeout_entries;
create policy "Public can delete closeout entries"
  on public.closeout_entries for delete to anon, authenticated using (true);

drop policy if exists "Public can read extranet hotels" on public.extranet_hotels;
create policy "Public can read extranet hotels"
  on public.extranet_hotels for select to anon, authenticated using (true);

drop policy if exists "Public can insert extranet hotels" on public.extranet_hotels;
create policy "Public can insert extranet hotels"
  on public.extranet_hotels for insert to anon, authenticated with check (true);

drop policy if exists "Public can update extranet hotels" on public.extranet_hotels;
create policy "Public can update extranet hotels"
  on public.extranet_hotels for update to anon, authenticated using (true) with check (true);

drop policy if exists "Public can delete extranet hotels" on public.extranet_hotels;
create policy "Public can delete extranet hotels"
  on public.extranet_hotels for delete to anon, authenticated using (true);

alter table public.closeout_entries replica identity full;
alter table public.extranet_hotels replica identity full;

alter publication supabase_realtime add table public.closeout_entries;
alter publication supabase_realtime add table public.extranet_hotels;
